<a href="https://colab.research.google.com/github/vinovijay7833/BLACK_FRIDAY/blob/main/Black_Friday.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BLACK Friday EDA AND FEATURE ENGINEERING-Problem Statement
A retail company “ABC Private Limited” wants to understand the customer purchase behaviour (specifically, purchase amount) against various products of different categories. They have shared purchase summary of various customers for selected high volume products from last month. The data set also contains customer demographics (age, gender, marital status, city_type, stay_in_current_city), product details (product_id and product category) and Total purchase_amount from last month.

Now, they want to build a model to predict the purchase amount of customer against various products which will help them to create personalized offer for customers against different products.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
tn=pd.read_csv("/content/train.csv")

In [4]:
tn.head(5)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0

In [5]:
tn.isnull().sum()

User_ID                           0
Product_ID                        0
Gender                            0
Age                               0
Occupation                        1
City_Category                     1
Stay_In_Current_City_Years        1
Marital_Status                    1
Product_Category_1                1
Product_Category_2             7215
Product_Category_3            15803
Purchase                          1
dtype: int64

In [6]:
tn.size

271068

In [7]:
tt=pd.read_csv("/content/test.csv")

In [8]:
tt.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3'],
      dtype='object')

In [9]:
tn.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [10]:
df=tn.append(tt)

<ipython-input-10-aa77ccd555b0>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=tn.append(tt)

In [11]:
df.tail(5)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
51027,1000649,P00331942,M,26-35,4.0,B,2,1.0,5.0,NaN,NaN,NaN
51028,1000651,P00004542,M,36-45,7.0,B,2,0.0,5.0,8.0,NaN,NaN
51029,1000651,P00220142,M,36-45,7.0,B,2,0.0,1.0,15.0,NaN,NaN
51030,1000651,P00190842,M,36-45,7.0,B,2,0.0,2.0,5.0,12.0,NaN
51031,1000651,P001766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.drop(["User_ID"],axis=1,inplace=True)

Handling catagorical features

In [13]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0
...,...,...,...,...,...,...,...,...,...,...,...
51027,P00331942,M,26-35,4.0,B,2,1.0,5.0,NaN,NaN,NaN
51028,P00004542,M,36-45,7.0,B,2,0.0,5.0,8.0,NaN,NaN
51029,P00220142,M,36-45,7.0,B,2,0.0,1.0,15.0,NaN,NaN
51030,P00190842,M,36-45,7.0,B,2,0.0,2.0,5.0,12.0,NaN
51031,P001766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
c=pd.get_dummies(df['Gender'],drop_first=1)

In [15]:
c

       M
0      0
1      0
2      0
3      0
4      1
...   ..
51027  1
51028  1
51029  1
51030  1
51031  0

[73621 rows x 1 columns]

In [16]:
df["Gender"]=c

In [17]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,0,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,P00248942,0,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,P00087842,0,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,P00085442,0,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,P00285442,1,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0

In [18]:
df["Age"]

0         0-17
1         0-17
2         0-17
3         0-17
4          55+
         ...
51027    26-35
51028    36-45
51029    36-45
51030    36-45
51031      NaN
Name: Age, Length: 73621, dtype: object

In [19]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,0,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,P00248942,0,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,P00087842,0,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,P00085442,0,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,P00285442,1,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0

In [20]:
df["City_Category"].unique()

array(['A', 'C', 'B', nan], dtype=object)

In [21]:
city_new=pd.get_dummies(df["City_Category"],drop_first=1)

In [22]:
city_new

       B  C
0      0  0
1      0  0
2      0  0
3      0  0
4      0  1
...   .. ..
51027  1  0
51028  1  0
51029  1  0
51030  1  0
51031  0  0

[73621 rows x 2 columns]

In [23]:
df=pd.concat([df,city_new],axis=1)

In [24]:
df.head(3)

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0,0,0
1,P00248942,0,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0,0,0
2,P00087842,0,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0,0,0

In [25]:
df.drop(["City_Category"],axis=1,inplace=True)

In [26]:
df

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10.0,2,0.0,3.0,NaN,NaN,8370.0,0,0
1,P00248942,0,0-17,10.0,2,0.0,1.0,6.0,14.0,15200.0,0,0
2,P00087842,0,0-17,10.0,2,0.0,12.0,NaN,NaN,1422.0,0,0
3,P00085442,0,0-17,10.0,2,0.0,12.0,14.0,NaN,1057.0,0,0
4,P00285442,1,55+,16.0,4+,0.0,8.0,NaN,NaN,7969.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
51027,P00331942,1,26-35,4.0,2,1.0,5.0,NaN,NaN,NaN,1,0
51028,P00004542,1,36-45,7.0,2,0.0,5.0,8.0,NaN,NaN,1,0
51029,P00220142,1,36-45,7.0,2,0.0,1.0,15.0,NaN,NaN,1,0
51030,P00190842,1,36-45,7.0,2,0.0,2.0,5.0,12.0,NaN,1,0
51031,P001766,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

## MISSING VALUES

In [27]:
df.isnull().sum()

Product_ID                        0
Gender                            0
Age                               1
Occupation                        2
Stay_In_Current_City_Years        2
Marital_Status                    2
Product_Category_1                2
Product_Category_2            22953
Product_Category_3            51290
Purchase                      51033
B                                 0
C                                 0
dtype: int64

In [28]:
df["Product_Category_1"].unique()

array([ 3.,  1., 12.,  8.,  5.,  4.,  2.,  6., 14., 11., 13., 15.,  7.,
       16., 18., 10., 17.,  9., nan])

In [29]:
df["Product_Category_2"].unique()

array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [30]:
df["Product_Category_3"].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

##MODE-DISCRETE

In [31]:
df["Product_Category_2"].mode()[0]

8.0

In [32]:
df["Product_Category_2"]=df["Product_Category_2"].fillna(df["Product_Category_2"].mode()[0])

In [33]:
df.head(3)

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10.0,2,0.0,3.0,8.0,NaN,8370.0,0,0
1,P00248942,0,0-17,10.0,2,0.0,1.0,6.0,14.0,15200.0,0,0
2,P00087842,0,0-17,10.0,2,0.0,12.0,8.0,NaN,1422.0,0,0

In [34]:
df["Product_Category_2"].isnull().sum()

0

In [35]:
df["Product_Category_3"]=df["Product_Category_3"].fillna(df["Product_Category_3"].mode()[0])

In [36]:
df["Product_Category_3"].isnull().sum()

0

In [37]:
df.head()

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10.0,2,0.0,3.0,8.0,16.0,8370.0,0,0
1,P00248942,0,0-17,10.0,2,0.0,1.0,6.0,14.0,15200.0,0,0
2,P00087842,0,0-17,10.0,2,0.0,12.0,8.0,16.0,1422.0,0,0
3,P00085442,0,0-17,10.0,2,0.0,12.0,14.0,16.0,1057.0,0,0
4,P00285442,1,55+,16.0,4+,0.0,8.0,8.0,16.0,7969.0,0,1

In [38]:
df["Stay_In_Current_City_Years"].unique()

array(['2', '4+', '3', '1', '0', nan], dtype=object)

In [39]:
df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].str.replace("+","")

<ipython-input-39-d114f8657c51>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].str.replace("+","")

In [40]:
df["Stay_In_Current_City_Years"].index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            51022, 51023, 51024, 51025, 51026, 51027, 51028, 51029, 51030,
            51031],
           dtype='int64', length=73621)

In [41]:
df.head(5)

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10.0,2,0.0,3.0,8.0,16.0,8370.0,0,0
1,P00248942,0,0-17,10.0,2,0.0,1.0,6.0,14.0,15200.0,0,0
2,P00087842,0,0-17,10.0,2,0.0,12.0,8.0,16.0,1422.0,0,0
3,P00085442,0,0-17,10.0,2,0.0,12.0,14.0,16.0,1057.0,0,0
4,P00285442,1,55+,16.0,4,0.0,8.0,8.0,16.0,7969.0,0,1

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73619 non-null  float64
 4   Stay_In_Current_City_Years  73619 non-null  object
 5   Marital_Status              73619 non-null  float64
 6   Product_Category_1          73619 non-null  float64
 7   Product_Category_2          73621 non-null  float64
 8   Product_Category_3          73621 non-null  float64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(6), object(3), uint8(3)
memory usage: 5.8+ MB

In [90]:
df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].astype(int)

ValueError: ignored

In [43]:
df["Stay_In_Current_City_Years"].isnull().sum()

2

In [44]:
df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].fillna(df['Stay_In_Current_City_Years'].mode()[0])

In [45]:
df["Stay_In_Current_City_Years"].isnull().sum()

0

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73619 non-null  float64
 4   Stay_In_Current_City_Years  73621 non-null  object
 5   Marital_Status              73619 non-null  float64
 6   Product_Category_1          73619 non-null  float64
 7   Product_Category_2          73621 non-null  float64
 8   Product_Category_3          73621 non-null  float64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(6), object(3), uint8(3)
memory usage: 5.8+ MB

In [47]:
df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].astype(int)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73619 non-null  float64
 4   Stay_In_Current_City_Years  73621 non-null  int64
 5   Marital_Status              73619 non-null  float64
 6   Product_Category_1          73619 non-null  float64
 7   Product_Category_2          73621 non-null  float64
 8   Product_Category_3          73621 non-null  float64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(6), int64(1), object(2), uint8(3)
memory usage: 5.8+ MB

In [49]:
df.isnull().sum()

Product_ID                        0
Gender                            0
Age                               1
Occupation                        2
Stay_In_Current_City_Years        0
Marital_Status                    2
Product_Category_1                2
Product_Category_2                0
Product_Category_3                0
Purchase                      51033
B                                 0
C                                 0
dtype: int64

In [50]:
df["Occupation"]=df["Occupation"].fillna(df["Occupation"].mode()[0])

In [51]:
df['Marital_Status']=df['Marital_Status'].fillna(df['Marital_Status'].mode()[0])

In [52]:
df['Product_Category_1']=df['Product_Category_1'].fillna(df['Product_Category_1'].mode()[0])

In [53]:
df.isnull().sum()

Product_ID                        0
Gender                            0
Age                               1
Occupation                        0
Stay_In_Current_City_Years        0
Marital_Status                    0
Product_Category_1                0
Product_Category_2                0
Product_Category_3                0
Purchase                      51033
B                                 0
C                                 0
dtype: int64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73621 non-null  float64
 4   Stay_In_Current_City_Years  73621 non-null  int64
 5   Marital_Status              73621 non-null  float64
 6   Product_Category_1          73621 non-null  float64
 7   Product_Category_2          73621 non-null  float64
 8   Product_Category_3          73621 non-null  float64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(6), int64(1), object(2), uint8(3)
memory usage: 5.8+ MB

In [55]:
df["Product_ID"].isnull().sum()

0

In [56]:
df["Product_ID"]=df["Product_ID"].fillna(df["Product_ID"].mode()[0])

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73621 non-null  float64
 4   Stay_In_Current_City_Years  73621 non-null  int64
 5   Marital_Status              73621 non-null  float64
 6   Product_Category_1          73621 non-null  float64
 7   Product_Category_2          73621 non-null  float64
 8   Product_Category_3          73621 non-null  float64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(6), int64(1), object(2), uint8(3)
memory usage: 5.8+ MB

In [58]:
df['Marital_Status']=df['Marital_Status'].astype(int)

In [59]:
df["Product_Category_1"]=df["Product_Category_1"].astype(int)

In [60]:
df["Product_Category_2"]=df["Product_Category_2"].astype(int)

In [61]:
df["Product_Category_3"]=df["Product_Category_3"].astype(int)

In [62]:
df["Occupation"]=df["Occupation"].astype(int)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  uint8
 2   Age                         73620 non-null  object
 3   Occupation                  73621 non-null  int64
 4   Stay_In_Current_City_Years  73621 non-null  int64
 5   Marital_Status              73621 non-null  int64
 6   Product_Category_1          73621 non-null  int64
 7   Product_Category_2          73621 non-null  int64
 8   Product_Category_3          73621 non-null  int64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  uint8
 11  C                           73621 non-null  uint8
dtypes: float64(1), int64(6), object(2), uint8(3)
memory usage: 5.8+ MB

In [64]:
df["B"]=df["B"].astype(int)

In [65]:
df["C"]=df["C"].astype(int)

In [66]:
df["Gender"]=df["Gender"].astype(int)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73621 entries, 0 to 51031
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  73621 non-null  object
 1   Gender                      73621 non-null  int64
 2   Age                         73620 non-null  object
 3   Occupation                  73621 non-null  int64
 4   Stay_In_Current_City_Years  73621 non-null  int64
 5   Marital_Status              73621 non-null  int64
 6   Product_Category_1          73621 non-null  int64
 7   Product_Category_2          73621 non-null  int64
 8   Product_Category_3          73621 non-null  int64
 9   Purchase                    22588 non-null  float64
 10  B                           73621 non-null  int64
 11  C                           73621 non-null  int64
dtypes: float64(1), int64(9), object(2)
memory usage: 7.3+ MB

In [69]:
sns.barplot("Age","Purchase",hue="Gender",data=df)

TypeError: ignored

In [70]:
sns.barplot('Age','Purchase',hue='Gender',data=df)

TypeError: ignored

In [73]:
sns.barplot('Product_Category_1',data=df)

TypeError: ignored

features scale

In [76]:
df[df["Purchase"].isnull()]

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
22588,P00005042,0,26-,4,1,0,5,8,16,NaN,0,0
0,P00128942,1,46-50,7,2,1,1,11,16,NaN,1,0
1,P00113442,1,26-35,17,0,0,3,5,16,NaN,0,1
2,P00288442,0,36-45,1,4,1,5,14,16,NaN,1,0
3,P00145342,0,36-45,1,4,1,4,9,16,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
51027,P00331942,1,26-35,4,2,1,5,8,16,NaN,1,0
51028,P00004542,1,36-45,7,2,0,5,8,16,NaN,1,0
51029,P00220142,1,36-45,7,2,0,1,15,16,NaN,1,0
51030,P00190842,1,36-45,7,2,0,2,5,12,NaN,1,0
51031,P001766,0,NaN,4,1,0,5,8,16,NaN,0,0

In [79]:
tt=df[df["Purchase"].isnull()]

In [80]:
tt

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
22588,P00005042,0,26-,4,1,0,5,8,16,NaN,0,0
0,P00128942,1,46-50,7,2,1,1,11,16,NaN,1,0
1,P00113442,1,26-35,17,0,0,3,5,16,NaN,0,1
2,P00288442,0,36-45,1,4,1,5,14,16,NaN,1,0
3,P00145342,0,36-45,1,4,1,4,9,16,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
51027,P00331942,1,26-35,4,2,1,5,8,16,NaN,1,0
51028,P00004542,1,36-45,7,2,0,5,8,16,NaN,1,0
51029,P00220142,1,36-45,7,2,0,1,15,16,NaN,1,0
51030,P00190842,1,36-45,7,2,0,2,5,12,NaN,1,0
51031,P001766,0,NaN,4,1,0,5,8,16,NaN,0,0

In [81]:
tn=df[~df["Purchase"].isnull()]

In [82]:
tn

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,B,C
0,P00069042,0,0-17,10,2,0,3,8,16,8370.0,0,0
1,P00248942,0,0-17,10,2,0,1,6,14,15200.0,0,0
2,P00087842,0,0-17,10,2,0,12,8,16,1422.0,0,0
3,P00085442,0,0-17,10,2,0,12,14,16,1057.0,0,0
4,P00285442,1,55+,16,4,0,8,8,16,7969.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
22583,P00346842,0,26-35,4,1,1,11,8,16,4491.0,0,0
22584,P00135242,0,26-35,4,1,1,4,5,13,2768.0,0,0
22585,P00151342,0,26-35,4,1,1,7,8,16,16677.0,0,0
22586,P00015942,0,26-35,4,1,1,6,10,13,16123.0,0,0
22587,P00303942,0,26-35,4,1,1,8,13,16,3896.0,0,0

In [83]:
tn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22588 entries, 0 to 22587
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  22588 non-null  object
 1   Gender                      22588 non-null  int64
 2   Age                         22588 non-null  object
 3   Occupation                  22588 non-null  int64
 4   Stay_In_Current_City_Years  22588 non-null  int64
 5   Marital_Status              22588 non-null  int64
 6   Product_Category_1          22588 non-null  int64
 7   Product_Category_2          22588 non-null  int64
 8   Product_Category_3          22588 non-null  int64
 9   Purchase                    22588 non-null  float64
 10  B                           22588 non-null  int64
 11  C                           22588 non-null  int64
dtypes: float64(1), int64(9), object(2)
memory usage: 2.2+ MB

In [84]:
tn.isnull().sum()

Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
B                             0
C                             0
dtype: int64

In [85]:
tt.isnull().sum()

Product_ID                        0
Gender                            0
Age                               1
Occupation                        0
Stay_In_Current_City_Years        0
Marital_Status                    0
Product_Category_1                0
Product_Category_2                0
Product_Category_3                0
Purchase                      51033
B                                 0
C                                 0
dtype: int64

In [88]:
tt["Age"]=tt["Age"].fillna(df["Age"].mode()[0])

<ipython-input-88-1d4a366e11c8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt["Age"]=tt["Age"].fillna(df["Age"].mode()[0])

In [89]:
tt.isnull().sum()

Product_ID                        0
Gender                            0
Age                               0
Occupation                        0
Stay_In_Current_City_Years        0
Marital_Status                    0
Product_Category_1                0
Product_Category_2                0
Product_Category_3                0
Purchase                      51033
B                                 0
C                                 0
dtype: int64